name: car_manager
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  go_router: ^13.0.1
  url_launcher: ^6.1.11
  shimmer: ^3.0.0
  get: ^4.6.6
  flutter_localizations:
    sdk: flutter
  intl: any
  http_parser: ^4.0.2
  path: ^1.8.3
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.7
  web_socket_channel: ^2.4.0
  flutter_local_notifications: ^16.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-RegularItalic.otf
          style: italic
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
